module.exports = {
	GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
	GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
	MONGO_URI: process.env.MONGO_URI,
	SESSION_SECRET: process.env.SESSION_SECRET
}